// <auto-generated />
using System;
using DiarioBordo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiarioBordo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251018003405_CargaPlanetas")]
    partial class CargaPlanetas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("DiarioBordo.Models.Missao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NaveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeMissao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroMissao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlanetaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NaveId");

                    b.HasIndex("PlanetaId");

                    b.ToTable("Missoes");
                });

            modelBuilder.Entity("DiarioBordo.Models.Nave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Naves");
                });

            modelBuilder.Entity("DiarioBordo.Models.Planeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Planetas");
                });

            modelBuilder.Entity("DiarioBordo.Models.Tripulante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NaveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NaveId");

                    b.ToTable("Tripulantes");
                });

            modelBuilder.Entity("DiarioBordo.Models.Missao", b =>
                {
                    b.HasOne("DiarioBordo.Models.Nave", "NaveNavigation")
                        .WithMany("Missoes")
                        .HasForeignKey("NaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiarioBordo.Models.Planeta", "PlanetaNavigation")
                        .WithMany("Missoes")
                        .HasForeignKey("PlanetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NaveNavigation");

                    b.Navigation("PlanetaNavigation");
                });

            modelBuilder.Entity("DiarioBordo.Models.Tripulante", b =>
                {
                    b.HasOne("DiarioBordo.Models.Nave", null)
                        .WithMany("Tripulantes")
                        .HasForeignKey("NaveId");
                });

            modelBuilder.Entity("DiarioBordo.Models.Nave", b =>
                {
                    b.Navigation("Missoes");

                    b.Navigation("Tripulantes");
                });

            modelBuilder.Entity("DiarioBordo.Models.Planeta", b =>
                {
                    b.Navigation("Missoes");
                });
#pragma warning restore 612, 618
        }
    }
}
